[package]
name = "table_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.40"
syn = "2.0.100"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proc-macro2 = "1.0"


[dev-dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
