use super::service::create_person;
use super::table_data::Person;
use dioxus::prelude::*;
use reslt_core::prelude::*;

#[component]
pub fn ModalCreate() -> Element {
    let modal = use_context::<UseModal>().to_owned();
    let toast = use_context::<UseToast>().to_owned();

    // Form state
    let mut name = use_signal(|| String::new());
    let mut age = use_signal(|| String::new());
    let mut city = use_signal(|| String::new());

    let is_submitting = use_signal(|| false);

    rsx! {
        form {
            class: "space-y-4",
            onsubmit: move |e: FormEvent| {
                e.prevent_default();

                if is_submitting() {
                    return;
                }

                *is_submitting.write() = true;

                let name_value = name.read().clone();
                let age_value = age.read().clone();
                let city_value = city.read().clone();
                let modal_clone = modal.clone();
                let toast_clone = toast.clone();

                // Validate inputs
                let age_parsed = age_value.parse::<u32>();

                if name_value.is_empty() {
                    toast_clone.error("Name is required");
                    *is_submitting.write() = false;
                    return;
                }

                if let Err(_) = age_parsed {
                    toast_clone.error("Age must be a valid number");
                    *is_submitting.write() = false;
                    return;
                }

                let age = age_parsed.unwrap();

                if city_value.is_empty() {
                    toast_clone.error("City is required");
                    *is_submitting.write() = false;
                    return;
                }

                // Create person
                let person = Person {
                    id: 0, // ID will be generated by the backend
                    name: name_value,
                    age,
                    city: city_value,
                    created_at: chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string(),
                    updated_at: chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string(),
                };

                // Spawn async task
                dioxus::prelude::spawn(async move {
                    match create_person(person).await {
                        Ok(_) => {
                            toast_clone.success("Person created successfully");
                            modal_clone.close();

                            // Clear form - this needs to be done in a synchronous context
                            // We'll handle this through a signal instead
                        },
                        Err(e) => {
                            toast_clone.error(&format!("Failed to create person: {}", e));
                        }
                    }
                    // Reset submitting state
                    // This needs to be done in the main thread context
                });

                // Clear form immediately after spawning the task
                // and reset submitting state after a delay
                let mut name_signal = name.clone();
                let mut age_signal = age.clone();
                let mut city_signal = city.clone();
                let mut is_submitting_signal = is_submitting.clone();

                dioxus::prelude::spawn(async move {
                    async_std::task::sleep(std::time::Duration::from_secs(2)).await;
                    name_signal.set(String::new());
                    age_signal.set(String::new());
                    city_signal.set(String::new());
                    is_submitting_signal.set(false);
                });
            },

            // Name field
            div {
                label {
                    class: "block text-sm font-medium text-gray-700",
                    for: "name",
                    "Name"
                }
                input {
                    id: "name",
                    r#type: "text",
                    class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2 border",
                    placeholder: "Enter name",
                    value: "{name}",
                    oninput: move |e| {
                        *name.write() = e.value();
                    }
                }
            }

            // Age field
            div {
                label {
                    class: "block text-sm font-medium text-gray-700",
                    for: "age",
                    "Age"
                }
                input {
                    id: "age",
                    r#type: "number",
                    min: "0",
                    class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2 border",
                    placeholder: "Enter age",
                    value: "{age}",
                    oninput: move |e| {
                        *age.write() = e.value();
                    }
                }
            }

            // City field
            div {
                label {
                    class: "block text-sm font-medium text-gray-700",
                    for: "city",
                    "City"
                }
                input {
                    id: "city",
                    r#type: "text",
                    class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2 border",
                    placeholder: "Enter city",
                    value: "{city}",
                    oninput: move |e| {
                        *city.write() = e.value();
                    }
                }
            }

            // Submit button
            div {
                class: "flex justify-end space-x-2",
                button {
                    r#type: "button",
                    class: "px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500",
                    onclick: move |_| {
                        modal.close();
                    },
                    "Cancel"
                }
                button {
                    r#type: "submit",
                    class: "px-4 py-2 border border-transparent rounded-md text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed",
                    disabled: is_submitting(),
                    if is_submitting() {
                        "Creating..."
                    } else {
                        "Create"
                    }
                }
            }
        }
    }
}
