name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Add repositories and install missing packages
      run: |
        sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu focal main universe'
        sudo apt-get update
        sudo apt-get install -y libjavascriptcoregtk-4.0-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
