name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add repositories and install missing packages
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.1-dev libgtk-3-dev libgdk-3-dev libxdo-dev zlib1g-dev


    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
